apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  namespace: $NS
  labels:
    app: prometheus
    component: core
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
    - name: webui
      protocol: TCP
      port: $SERVICE_PORT
      targetPort: 9090
  selector:
    app: prometheus
    component: core
